delay:
  action: -0
  observation: -0
frequnecy: 
  frameskip_custom: 32
  freq: 62.5
target_vel:
  x: 0.5
result:
  sim: /home/dyros/tocabi_ws/src/tocabi_cc/result/iserdata_ppt/data_250_speed0.5.csv
  real: /home/dyros/catkin_ws/data_